### PR TITLE
Add values  for function timeout and scaling settings

### PR DESCRIPTION
**Pull request by welteki**
Signed-off-by: Han Verstraete (OpenFaaS Ltd) <han@openfaas.com>

## Description

Add values  for function timeout and scaling settings

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## How Has This Been Tested?

Deployed OpenFaaS functions and validated output

Screenshot 2022-09-05 at 15 55 47

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
We need a rebase on this please.

**Comment by alexellis** [comment]
Can you put a space between the main metadata and the scaling config?

Also don't print any scaling info if nothing is set at all?

"No scaling configuration was set"

**Comment by welteki** [comment]
The new output with changes applied.

Screenshot 2022-09-05 at 16 34 00

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
